#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/sony/extras

PRODUCT_COPY_FILES += \
    vendor/sony/extras/proprietary/product/etc/default-permissions/default-permissions_com.sonymobile.gps.extension.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/default-permissions/default-permissions_com.sonymobile.gps.extension.xml \
    vendor/sony/extras/proprietary/product/etc/permissions/com.sony.360ra.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.sony.360ra.xml \
    vendor/sony/extras/proprietary/product/etc/permissions/com.sony.threesixtyra.audiofx.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.sony.threesixtyra.audiofx.xml \
    vendor/sony/extras/proprietary/product/etc/permissions/com.sonyericsson.music.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.sonyericsson.music.xml \
    vendor/sony/extras/proprietary/product/etc/permissions/com.sonymobile.extmonitorapp.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.sonymobile.extmonitorapp.xml \
    vendor/sony/extras/proprietary/product/etc/permissions/com.sonymobile.moviecreator.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.sonymobile.moviecreator.xml \
    vendor/sony/extras/proprietary/product/etc/permissions/com.sonymobile.photopro.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.sonymobile.photopro.xml \
    vendor/sony/extras/proprietary/product/etc/permissions/jp.co.sony.mc.usbextoutaudio.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/jp.co.sony.mc.usbextoutaudio.xml \
    vendor/sony/extras/proprietary/product/etc/permissions/jp.co.sony.threesixtyra.system.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/jp.co.sony.threesixtyra.system.xml \
    vendor/sony/extras/proprietary/product/etc/permissions/privapp-permissions_com.sonymobile.gps.extension.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/privapp-permissions_com.sonymobile.gps.extension.xml \
    vendor/sony/extras/proprietary/system/usr/keylayout/AVRCP.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/AVRCP.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Generic.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Generic.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0079_Product_0011.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0079_Product_0011.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0079_Product_18d4.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0079_Product_18d4.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0171_Product_0419.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0171_Product_0419.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0428_Product_4001.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0428_Product_4001.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_044f_Product_b326.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_044f_Product_b326.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_045e_Product_028e.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_045e_Product_028e.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_045e_Product_028f.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_045e_Product_028f.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_045e_Product_02a1.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_045e_Product_02a1.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_045e_Product_02d1.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_045e_Product_02d1.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_045e_Product_02dd.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_045e_Product_02dd.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_045e_Product_02e0.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_045e_Product_02e0.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_045e_Product_02e3.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_045e_Product_02e3.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_045e_Product_02ea.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_045e_Product_02ea.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_045e_Product_02fd.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_045e_Product_02fd.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_045e_Product_0b12.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_045e_Product_0b12.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_046d_Product_b501.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_046d_Product_b501.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_046d_Product_c216.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_046d_Product_c216.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_046d_Product_c219.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_046d_Product_c219.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_046d_Product_c21d.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_046d_Product_c21d.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_046d_Product_c21e.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_046d_Product_c21e.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_046d_Product_c21f.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_046d_Product_c21f.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_046d_Product_c242.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_046d_Product_c242.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_046d_Product_c294.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_046d_Product_c294.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_046d_Product_c299.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_046d_Product_c299.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_046d_Product_c532.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_046d_Product_c532.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_054c_Product_0268.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_054c_Product_0268.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_054c_Product_0268_Version_8000.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_054c_Product_0268_Version_8000.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_054c_Product_0268_Version_8100.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_054c_Product_0268_Version_8100.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_054c_Product_0268_Version_8111.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_054c_Product_0268_Version_8111.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_054c_Product_05c4.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_054c_Product_05c4.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_054c_Product_05c4_Version_8000.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_054c_Product_05c4_Version_8000.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_054c_Product_05c4_Version_8100.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_054c_Product_05c4_Version_8100.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_054c_Product_05c4_Version_8111.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_054c_Product_05c4_Version_8111.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_054c_Product_09cc.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_054c_Product_09cc.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_054c_Product_09cc_Version_8000.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_054c_Product_09cc_Version_8000.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_054c_Product_09cc_Version_8100.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_054c_Product_09cc_Version_8100.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_054c_Product_09cc_Version_8111.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_054c_Product_09cc_Version_8111.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_054c_Product_0ba0.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_054c_Product_0ba0.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_054c_Product_0ba0_Version_8111.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_054c_Product_0ba0_Version_8111.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_054c_Product_0ce6.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_054c_Product_0ce6.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_054c_Product_0ce6_fallback.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_054c_Product_0ce6_fallback.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_054c_Product_0df2.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_054c_Product_0df2.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_054c_Product_0df2_fallback.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_054c_Product_0df2_fallback.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_056e_Product_2004.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_056e_Product_2004.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_056e_Product_2010.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_056e_Product_2010.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_056e_Product_2013.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_056e_Product_2013.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_057e_Product_2009.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_057e_Product_2009.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0583_Product_2060.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0583_Product_2060.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_05ac_Product_0239.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_05ac_Product_0239.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_06a3_Product_f51a.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_06a3_Product_f51a.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0738_Product_4716.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0738_Product_4716.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0738_Product_4718.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0738_Product_4718.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0738_Product_4726.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0738_Product_4726.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0738_Product_4736.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0738_Product_4736.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0738_Product_4740.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0738_Product_4740.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0738_Product_9871.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0738_Product_9871.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0738_Product_b726.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0738_Product_b726.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0738_Product_beef.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0738_Product_beef.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0738_Product_cb02.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0738_Product_cb02.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0738_Product_cb03.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0738_Product_cb03.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0738_Product_cb29.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0738_Product_cb29.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0738_Product_f738.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0738_Product_f738.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_07ff_Product_ffff.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_07ff_Product_ffff.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0957_Product_0001.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0957_Product_0001.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0957_Product_0031.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0957_Product_0031.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0b05_Product_4500.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0b05_Product_4500.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0e6f_Product_0113.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0e6f_Product_0113.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0e6f_Product_011f.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0e6f_Product_011f.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0e6f_Product_0131.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0e6f_Product_0131.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0e6f_Product_0133.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0e6f_Product_0133.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0e6f_Product_0139.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0e6f_Product_0139.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0e6f_Product_013a.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0e6f_Product_013a.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0e6f_Product_0146.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0e6f_Product_0146.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0e6f_Product_0147.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0e6f_Product_0147.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0e6f_Product_0161.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0e6f_Product_0161.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0e6f_Product_0162.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0e6f_Product_0162.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0e6f_Product_0163.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0e6f_Product_0163.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0e6f_Product_0164.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0e6f_Product_0164.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0e6f_Product_0165.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0e6f_Product_0165.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0e6f_Product_0201.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0e6f_Product_0201.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0e6f_Product_0213.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0e6f_Product_0213.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0e6f_Product_021f.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0e6f_Product_021f.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0e6f_Product_0246.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0e6f_Product_0246.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0e6f_Product_02a4.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0e6f_Product_02a4.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0e6f_Product_02a6.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0e6f_Product_02a6.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0e6f_Product_02ab.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0e6f_Product_02ab.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0e6f_Product_0301.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0e6f_Product_0301.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0e6f_Product_0346.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0e6f_Product_0346.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0e6f_Product_0401.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0e6f_Product_0401.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0e6f_Product_0413.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0e6f_Product_0413.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0e6f_Product_0501.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0e6f_Product_0501.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0e6f_Product_f501.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0e6f_Product_f501.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0e6f_Product_f900.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0e6f_Product_f900.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0f0d_Product_000a.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0f0d_Product_000a.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0f0d_Product_000c.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0f0d_Product_000c.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0f0d_Product_0067.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0f0d_Product_0067.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_0f0d_Product_00c1.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_0f0d_Product_00c1.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1038_Product_1412.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1038_Product_1412.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1038_Product_1430.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1038_Product_1430.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1038_Product_1431.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1038_Product_1431.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1038_Product_1434.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1038_Product_1434.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_11c9_Product_55f0.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_11c9_Product_55f0.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_12ab_Product_0301.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_12ab_Product_0301.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_12bd_Product_d015.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_12bd_Product_d015.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1430_Product_4748.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1430_Product_4748.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1430_Product_f801.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1430_Product_f801.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_146b_Product_0601.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_146b_Product_0601.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1532_Product_0037.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1532_Product_0037.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1532_Product_0705.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1532_Product_0705.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1532_Product_0707.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1532_Product_0707.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1532_Product_0709.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1532_Product_0709.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1532_Product_0900.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1532_Product_0900.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1532_Product_0a03.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1532_Product_0a03.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1532_Product_1004.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1532_Product_1004.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1532_Product_1007.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1532_Product_1007.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1532_Product_1009.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1532_Product_1009.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1532_Product_100a.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1532_Product_100a.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_15e4_Product_3f00.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_15e4_Product_3f00.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_15e4_Product_3f0a.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_15e4_Product_3f0a.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_15e4_Product_3f10.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_15e4_Product_3f10.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_162e_Product_beef.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_162e_Product_beef.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1689_Product_fd00.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1689_Product_fd00.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1689_Product_fd01.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1689_Product_fd01.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1689_Product_fe00.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1689_Product_fe00.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_18d1_Product_0200.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_18d1_Product_0200.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_18d1_Product_2c40.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_18d1_Product_2c40.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_18d1_Product_4f80.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_18d1_Product_4f80.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_18d1_Product_5018.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_18d1_Product_5018.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_18d1_Product_9451.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_18d1_Product_9451.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1949_Product_0401.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1949_Product_0401.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1bad_Product_0002.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1bad_Product_0002.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1bad_Product_f016.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1bad_Product_f016.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1bad_Product_f021.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1bad_Product_f021.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1bad_Product_f023.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1bad_Product_f023.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1bad_Product_f025.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1bad_Product_f025.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1bad_Product_f027.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1bad_Product_f027.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1bad_Product_f028.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1bad_Product_f028.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1bad_Product_f036.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1bad_Product_f036.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1bad_Product_f038.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1bad_Product_f038.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1bad_Product_f501.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1bad_Product_f501.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1bad_Product_f506.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1bad_Product_f506.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1bad_Product_f900.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1bad_Product_f900.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1bad_Product_f901.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1bad_Product_f901.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1bad_Product_f903.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1bad_Product_f903.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1bad_Product_f904.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1bad_Product_f904.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1bad_Product_fa01.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1bad_Product_fa01.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1bad_Product_fd00.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1bad_Product_fd00.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1bad_Product_fd01.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1bad_Product_fd01.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_1d79_Product_0009.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_1d79_Product_0009.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_22b8_Product_093d.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_22b8_Product_093d.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_2378_Product_1008.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_2378_Product_1008.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_2378_Product_100a.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_2378_Product_100a.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_24c6_Product_5300.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_24c6_Product_5300.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_24c6_Product_5303.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_24c6_Product_5303.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_24c6_Product_530a.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_24c6_Product_530a.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_24c6_Product_531a.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_24c6_Product_531a.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_24c6_Product_5397.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_24c6_Product_5397.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_24c6_Product_541a.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_24c6_Product_541a.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_24c6_Product_542a.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_24c6_Product_542a.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_24c6_Product_543a.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_24c6_Product_543a.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_24c6_Product_5500.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_24c6_Product_5500.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_24c6_Product_5501.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_24c6_Product_5501.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_24c6_Product_5506.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_24c6_Product_5506.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_24c6_Product_550d.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_24c6_Product_550d.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_24c6_Product_551a.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_24c6_Product_551a.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_24c6_Product_561a.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_24c6_Product_561a.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_24c6_Product_5b02.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_24c6_Product_5b02.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_24c6_Product_5d04.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_24c6_Product_5d04.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_24c6_Product_fafe.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_24c6_Product_fafe.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_27f8_Product_0bbe.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_27f8_Product_0bbe.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_27f8_Product_0bbf.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_27f8_Product_0bbf.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_28de_Product_1102.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_28de_Product_1102.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_2dc8_Product_6101.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_2dc8_Product_6101.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/Vendor_2e95_Product_7725.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/Vendor_2e95_Product_7725.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/gpio-keys.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/gpio-keys.kl \
    vendor/sony/extras/proprietary/system/usr/keylayout/idroid_con.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/idroid_con.kl \
    vendor/sony/extras/proprietary/system_ext/etc/default-permissions/exceptions-soundenhancement.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/default-permissions/exceptions-soundenhancement.xml \
    vendor/sony/extras/proprietary/system_ext/etc/default-permissions/privapp-exceptions-wirelessplayback.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/default-permissions/privapp-exceptions-wirelessplayback.xml \
    vendor/sony/extras/proprietary/system_ext/etc/permissions/com.dolby.daxservice.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.dolby.daxservice.xml \
    vendor/sony/extras/proprietary/system_ext/etc/permissions/com.sonyericsson.soundenhancement.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.sonyericsson.soundenhancement.xml \
    vendor/sony/extras/proprietary/system_ext/etc/permissions/com.sonymobile.audioutil.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.sonymobile.audioutil.xml \
    vendor/sony/extras/proprietary/system_ext/etc/permissions/com.sonymobile.gesdklibrary.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.sonymobile.gesdklibrary.xml \
    vendor/sony/extras/proprietary/system_ext/etc/permissions/privapp-permissions-aptxals.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/privapp-permissions-aptxals.xml \
    vendor/sony/extras/proprietary/system_ext/etc/permissions/privapp-permissions-aptxui.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/privapp-permissions-aptxui.xml \
    vendor/sony/extras/proprietary/system_ext/etc/permissions/privapp-permissions-wirelessplayback.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/privapp-permissions-wirelessplayback.xml \
    vendor/sony/extras/proprietary/system_ext/etc/sysconfig/config_com.sonyericsson.soundenhancement_preferences.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/sysconfig/config_com.sonyericsson.soundenhancement_preferences.xml \
    vendor/sony/extras/proprietary/vendor/etc/DrangeparaAAC128.bin:$(TARGET_COPY_OUT_VENDOR)/etc/DrangeparaAAC128.bin \
    vendor/sony/extras/proprietary/vendor/etc/DrangeparaAAC256.bin:$(TARGET_COPY_OUT_VENDOR)/etc/DrangeparaAAC256.bin \
    vendor/sony/extras/proprietary/vendor/etc/DrangeparaAAC64.bin:$(TARGET_COPY_OUT_VENDOR)/etc/DrangeparaAAC64.bin \
    vendor/sony/extras/proprietary/vendor/etc/DrangeparaMP3_128.bin:$(TARGET_COPY_OUT_VENDOR)/etc/DrangeparaMP3_128.bin \
    vendor/sony/extras/proprietary/vendor/etc/DrangeparaMP3_160.bin:$(TARGET_COPY_OUT_VENDOR)/etc/DrangeparaMP3_160.bin \
    vendor/sony/extras/proprietary/vendor/etc/DrangeparaMP3_192.bin:$(TARGET_COPY_OUT_VENDOR)/etc/DrangeparaMP3_192.bin \
    vendor/sony/extras/proprietary/vendor/etc/DrangeparaPCM441.bin:$(TARGET_COPY_OUT_VENDOR)/etc/DrangeparaPCM441.bin \
    vendor/sony/extras/proprietary/vendor/etc/DrangeparaPCM48.bin:$(TARGET_COPY_OUT_VENDOR)/etc/DrangeparaPCM48.bin \
    vendor/sony/extras/proprietary/vendor/etc/XTC_speaker_coef.hki:$(TARGET_COPY_OUT_VENDOR)/etc/XTC_speaker_coef.hki \
    vendor/sony/extras/proprietary/vendor/etc/alc.speaker.bin:$(TARGET_COPY_OUT_VENDOR)/etc/alc.speaker.bin \
    vendor/sony/extras/proprietary/vendor/etc/audio_app_white_list.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_app_white_list.xml \
    vendor/sony/extras/proprietary/vendor/etc/dolby/dax-default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.xml \
    vendor/sony/extras/proprietary/vendor/etc/dsx_param_file.bin:$(TARGET_COPY_OUT_VENDOR)/etc/dsx_param_file.bin \
    vendor/sony/extras/proprietary/vendor/etc/init/android.hardware.media.c2@1.0-threesixty-ra-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.media.c2@1.0-threesixty-ra-service.rc \
    vendor/sony/extras/proprietary/vendor/etc/init/vendor.dolby.hardware.dms@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.dolby.hardware.dms@2.0-service.rc \
    vendor/sony/extras/proprietary/vendor/etc/init/vendor.dolby.media.c2@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.dolby.media.c2@1.0-service.rc \
    vendor/sony/extras/proprietary/vendor/etc/media_codecs_dolby_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_dolby_audio.xml \
    vendor/sony/extras/proprietary/vendor/etc/media_codecs_sony_c2_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_sony_c2_audio.xml \
    vendor/sony/extras/proprietary/vendor/etc/seccomp_policy/android.hardware.media.c2@1.2-default-seccomp_policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/android.hardware.media.c2@1.2-default-seccomp_policy \
    vendor/sony/extras/proprietary/vendor/etc/windnoise_reduction.data:$(TARGET_COPY_OUT_VENDOR)/etc/windnoise_reduction.data \
    vendor/sony/extras/proprietary/vendor/etc/windnoise_reduction_back.data:$(TARGET_COPY_OUT_VENDOR)/etc/windnoise_reduction_back.data \
    vendor/sony/extras/proprietary/vendor/etc/windnoise_reduction_stat.data:$(TARGET_COPY_OUT_VENDOR)/etc/windnoise_reduction_stat.data \
    vendor/sony/extras/proprietary/vendor/etc/windnoise_reduction_stat_back.data:$(TARGET_COPY_OUT_VENDOR)/etc/windnoise_reduction_stat_back.data

PRODUCT_PACKAGES += \
    libXtcApi \
    libaudiokeymgr \
    libaudiosnpewrapper \
    libaudiosnpewrapper_context \
    libcodec2_soft_ac4dec \
    libcodec2_soft_ddpdec \
    libcodec2_soft_dolby \
    libcodec2_soft_mha1dec \
    libcodec2_soft_mhm1dec \
    libcodec2_store_dolby \
    libdapparamstorage \
    libdeccfg \
    libdlbdsservice \
    libdlbpreg \
    libiVptApi \
    libiVptHkiDec \
    libiVptLibC \
    liboem_specific \
    librebuffering \
    libthreesixty_ra_codec2_store \
    libtsrspkenhance \
    libupmix-lib \
    libznr \
    libbundlewrapper1 \
    libbundlewrapper2 \
    libbundlewrapper3 \
    libbundlewrapper4 \
    libdlbvol \
    libdnnrwrapper \
    libswdap \
    libswgamedap \
    libswvqe \
    libtsrspatializer \
    libtsrupmix \
    libznrwrapper \
    vendor.dolby.hardware.dms@2.0-impl \
    vendor.dolby.hardware.dms@2.0_vendor \
    libmepstarterjni \
    libmmparserextractor \
    libavenhancements \
    vendor.dolby.hardware.dms@2.0 \
    CameraExtensionsProxy \
    CameraAddonPermission \
    CameraCommonPermission \
    GamingAccessorySettings \
    GamingFanService \
    SomcCinemaPro \
    SomcDualshockManager \
    SomcVideoPro \
    ThermalFanService \
    ThreeSixtyRASettings \
    CameraCommon-Yodo \
    CameraPanorama-Yodo \
    ExtMonitorApp \
    SomcExtGps \
    SomcMovieCreator-AsahiYodo \
    SomcPhotoPro \
    ThreeSixtyRASystem \
    UsbExtOutAudio \
    aptxacu \
    DolbySound \
    ExtendedAudioService \
    SoundEnhancement \
    WirelessPlaybackQuality \
    aptxals \
    aptxui \
    daxService \
    com.sony.threesixtyra.audiofx \
    com.sonymobile.gesdklibrary \
    vendor.dolby.hardware.dms.xml \
    vendor.dolby.media.c2@1.0-service.xml \
    vendor.threesixty_ra.codec2.xml \
    android.hardware.media.c2@1.0-threesixty-ra-service \
    vendor.dolby.hardware.dms@2.0-service \
    vendor.dolby.media.c2@1.0-service \
    aptxalsOverlayCreateProject
